blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('post/<pk>/publish/', views.post_publish, name='post_publish'),
    path('post/<pk>/remove/', views.post_remove, name='post_remove'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.main_view, name='main'),
]

mapping/urls.py
from django.urls import path
from . import views

app_name = 'mapping'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('all/', views.mapping_list, name='all'),
    path('all/error/', views.page_error, name="error"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    path('blog/', include('blog.urls')),
    path('mapping/', include('mapping.urls')),
    path('str/', include('str.urls')),
    path('',include('home.urls')),
]

str/urls.py
from django.urls import path
from . import views

app_name = 'str'

urlpatterns = [
    path('', views.main_view, name='main'),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)    

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

home/models.py
from django.db import models

# Create your models here.

mapping/models.py
from django.db import models

# Create your models here.
class Full_table(models.Model):
    alias = models.CharField(max_length=128)
    feture_name = models.CharField(max_length=128)

    def __str__(self):
        return self.alias

class ID_table(models.Model):
    feture_name = models.CharField(max_length=128)

    def __str__(self):
        return self.feture_name

str/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms

from .models import Post, Comment

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text',)

blog/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Post, Comment
from django.shortcuts import render, get_object_or_404, redirect
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    return render(request, 'blog/post_draft_list.html', {'posts': posts})

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post_detail', pk=pk)

@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('post_list')

def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('blog:post_detail', pk=comment.post.pk)

home/views.py
from django.shortcuts import render

# Create your views here.
def main_view(request):
    return render(request, 'home/main_view.html', {})

mapping/views.py
from django.shortcuts import render, redirect, reverse
from .models import Full_table, ID_table
from django.http import HttpResponseRedirect
import pandas as pd
from itertools import chain

# Create your views here.
def handling_file(file):
    try:
        df = pd.read_excel(file,squeeze=True,header=None)
    except:
        print('error')
        data_list =None
        errors = None
        return data_list, errors
    data_list = df.tolist()
    data_list_o = data_list.copy()
    errors=[]
    for i,j in enumerate(data_list):
        data_list[i]= j.upper()
        if not ((Full_table.objects.filter(alias=data_list[i]).exists()) or (ID_table.objects.filter(feture_name=data_list[i]).exists())):
            if data_list_o[i] not in errors:
                errors.append(data_list_o[i])
    return data_list, errors


def home_view(request):
    if request.method == 'POST':
        try:
            file = request.FILES['file']
        except:
            return redirect(reverse('mapping:error')) # 防呆
        data_list, errors = handling_file(file)
        if (data_list is None )and (errors is None):
            return redirect(reverse('mapping:error'))  # 防呆
        ids1 = Full_table.objects.filter(alias__in=data_list)
        ids2 = ID_table.objects.filter(feture_name__in=data_list)
        ids = list(chain(ids1, ids2))
        return render(request, 'mapping/home.html', {'ids':ids ,'errors': errors})
    else:
        ids = None
        error = None
        return render(request,'mapping/home.html',{'ids':ids ,'errors':error})

def mapping_list(request):
    ids = Full_table.objects.all()
    return render(request,'mapping/list.html',{'ids':ids})

def page_error(request):
    return render(request,'mapping/error.html',{})

str/views.py
from django.shortcuts import render

# Create your views here.
def main_view(request):
    return render(request, 'str/main_view.html', {})

blog/templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<html>
    <head>
        <title>Django Girls blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
        <div class="page-header">
            {% if user.is_authenticated %}
                <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
                <a href="{% url 'blog:post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
                <p class="top-menu">Hello {{ user.username }} <small>(<a href="{% url 'logout' %}">Log out</a>)</small></p>
            {% else %}
                <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
            {% endif %}
            <h1><a href="{% url 'blog:post_list' %}">Django Girls Blog</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% else %}
            <a class="btn btn-default" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
        {% endif %}
        {% if user.is_authenticated %}
          <a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
          <a class="btn btn-default" href="{% url 'blog:post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
        {% endif %}
        <h2>{{ post.title }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
    <hr>
    <a class="btn btn-default" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add comment</a>
    {% for comment in post.comments.all %}
        {% if user.is_authenticated or comment.approved_comment %}
        <div class="comment">
            <div class="date">
                {{ comment.created_date }}
                {% if not comment.approved_comment %}
                    <a class="btn btn-default" href="{% url 'blog:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                    <a class="btn btn-default" href="{% url 'blog:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
                {% endif %}
            </div>
            <strong>{{ comment.author }}</strong>
            <p>{{ comment.text|linebreaks }}</p>
        </div>
        {% endif %}
    {% empty %}
        <p>No comments here yet :(</p>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <p class="date">created: {{ post.created_date|date:'d-m-Y' }}</p>
            <h1><a href="{% url 'blog:ost_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>New post</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
  {% for post in posts %}
      <div class="post">
          <div class="date">
              <p>published: {{ post.published_date }}</p>
          </div>
          <h2><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
          <p>{{ post.text|linebreaksbr }}</p>
          <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{ post.approved_comments.count }}</a>
      </div>
  {% endfor %}
{% endblock %}

home/templates/home/main_view.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>home_page</title>
    </head>
    <body>
        <div class="page-header">
            <h1>HOME PAGE</h1>
        </div>
        <div class="content container">
          <ul>
            <li><a href="{% url 'blog:post_list' %}">blog</a></li>
            <li><a href="{% url 'mapping:home' %}">mapping</a></li>
            <li><a href="{% url 'str:main' %}">str</a></li>
          </ul>
        </div>
    </body>
</html>

mapping/templates/mapping/base.html
{% load static %}
<html>
    <head>
        <title>Mapping ID</title>
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'css/mapping.css' %}">
        <style>
          table, th, td {
            width:100;
          }
        </style>
    </head>
    <body class ="mt-3 m-4 ">
        {% block content %}
        {% endblock %}
    </body>
</html>

mapping/templates/mapping/error.html
{% extends 'mapping/base.html' %}
{% block content %}
  <h1> File Error </h1>
  <p> If you see this page, please check your file type.</p>
  <p>File type must be ".xlsx" and you must need to opload a file</p>
  <a href="{% url 'mapping:home' %}">Go back</a>
{% endblock %}

mapping/templates/mapping/home.html
{% extends 'mapping/base.html' %}
{% block content %}
  <h1>Mapping ID</h1>
  <a href="{% url 'mapping:all' %}"> See Full Table </a>
  <form method="POST" enctype="multipart/form-data" >
  {% csrf_token %}
    <label for="myfile">Select a file:</label>
    <input type="file" name="file"><br><br>
    <input type="submit">
  </form>
  <table class="table table-bordered">
      <thead class = "thead-dark">
        <tr>
          <th>Input</th>
          <th>ID</th>
        <tr>
      </thead>
      {% for id in ids %}
        <tr>
          {% if id.alias %}
            <td>{{ id.alias }}</td>
          {% else %}
            <td>{{ id.feture_name }}</td>
          {% endif %}
          <td>{{id.feture_name}}</td>
        </tr>
      {% endfor %}
  </table>
  {% if errors %}
    <p>These item can't mapping:<br>
    {% for error in errors %}
      <small>{{error}}</small><br>
    {% endfor %}
    </p>
  {% endif %}
{% endblock %}

mapping/templates/mapping/list.html
{% extends 'mapping/base.html' %}
{% block content %}
  <h1>Full Table</h1>
  <a href="{% url 'mapping:home' %}"> Go home </a>
  <table class="table table-bordered">
        <thead class = "thead-dark">
          <tr>
            <th>Alias / Standard Name</th>
            <th>ID</th>
          <tr>
        </thead>
        {% for id in ids %}
          <tr>
            <td>{{ id.alias }}</td>
            <td>{{id.feture_name}}</td>
          </tr>
        {% endfor %}
  </table>
{% endblock %}

str/templates/str/main_view.html
<!DOCTYPE html>
<html>
  <head>

      <!-- Embed the STRING's javascript -->

      <script type="text/javascript" src="https://string-db.org/javascript/combined_embedded_network_v2.0.2.js"></script>

      <style>

           /* some styling */

           body {
               font-family: Arial;
               color: #122e4d;
               background: #cedded;
           }

           input {
               border: 4px solid #122e4d;
               width: 40%;
               height: 50px;
               border-radius: 10px;
               font-size: 20px;
           }

           button {
               font-size:20px;
               border-radius: 10px;
               border: 1px solid #122e4d;
           }

      </style>
      <script>
          function send_request_to_string() {

              var inputField = document.getElementById('inputarea');

              var text = inputField.value;

              if (!text) {text = inputField.placeholder}; // placeholder

              var proteins = text.split(' ');

              /* the actual API query */

              getSTRING('https://string-db.org', {
                          'species':'3702', //NCBI taxon identifiers (e.g. Human is 9606, see: STRING organisms).
                          'identifiers':proteins,
                          'network_flavor':'confidence',
                          'caller_identity': 'www.awesome_app.org'
              })

          }

      </script>
  </head>

  <!-- HTML CODE -->

  <body onload='javascript:send_request_to_string()'>
      <center>
          <h1>MY WEBSITE</h1>
          <h3>Query me: (<em>Arabidopsis thaliana</em> protein or multiple space seperated proteins)</h3>
             <input type="text" id='inputarea' placeholder='3702.AT1G50920.1'><br/></br/>
             <button onclick='javascript:send_request_to_string();' type="button">Let's go!</button>
             <h3>Network:</h3>
             <div id="stringEmbedded"></div>
      </center>
  </body>
</html>